# name: Deploy Frontend
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#       - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
#       - run: docker run -e CI=true cygnetops/react-test npm test

name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false  # Ensure tests run in CI mode

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploy steps go here"  # Replace with actual deployment commands
